### PR TITLE
Feature/backend skeleton

### PR DESCRIPTION
**Pull request by v1r7u**
The PR adds backend project skeleton. It includes:
- asp.net core 3.1 application
- swagger
- a sample landing-page endpoint
- readme with instructions how to run it locally

@detaybey take a look. If you have any proposals/requests, please let me know

### CODE REVIEW

**Comment by detaybey** [comment]
About the dates on overview/component score history, assuming that we always have the last 30 days is somehow broken. There may be skipped scans, duplicate scans, etc... For a proper display (we will also list these scans as a list i believe) we should have the date and score together like 
```scoreHistory = [(date1, score) , (date2, score) ....] ```

why do you think we would have duplicate dates?

**Comment by deepnetwork** [comment]
Not sure if date is required per se, but how would you address a scenario if someone wants to click on a particular historic result from the graphic?

**Comment by v1r7u** [comment]
> Not sure if date is required per se, but how would you address a scenario if someone wants to click on a particular historic result from the graphic?

It could be done based on these assumptions:
- response **always** has 30 values
- `scoreHistory[0]` **always** equal to `now - 30 days`
- score[29] **always** equal to `now` 

Then you can re-build actual dates on UI side, while response is not overloadded with data.
(to be safer, we could have added `StartingDate` to map the first values in area to exact point of time)

To give an example
1. The version without dates, for response with two subscriptions is `2Kb`;
2. The version with dates, for the same response it's already `10Kb`;
3. The version with dates, response with 10 subscriptions is `36Kb`.

That's not the end of the world, but I've thought it's simple enough optimization.

Nevertheless, **I committed the version with dates** and I'm merging the PR with it.

**Comment by deepnetwork** [comment]
> Nevertheless, **I committed the version with dates** and I'm merging the PR with it.

That's better,

**Pull request merged**
